import Navbar from "./components/Navbar/Navbar";
import "./globals.css";

import { Providers } from "./Redux/provider";

export const metadata = {
  title: "Jonathan Kim",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
